version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: habbit-postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: habbit
      POSTGRES_PASSWORD: habbit123
      POSTGRES_DB: habbit_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U habbit']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: habbit-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    command: redis-server --requirepass habbit123
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
      interval: 10s
      timeout: 3s
      retries: 5

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
